services:
  frontend:
    container_name: glygen-biomarker-dev
    image: glygen-biomarker-dev:latest
    build:
      args:
        - REACT_APP_ENV=biom_dev
        - REACT_APP_BUILD=biomarker
        - REACT_APP_API=https://api.dev.biomarkerkb.org
        - REACT_APP_DOMAIN=https://dev.biomarkerkb.org
        # - REACT_APP_DOMAIN=http://localhost:6060
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.dev.biomarkerkb.org
        - REACT_APP_SPARQL=https://sparql.glygen.org
        - REACT_APP_GITHUB=https://github.com/clinical-biomarkers/biomarker-partnership
        - REACT_APP_BIOMARKER_FAQ=https://data.dev.biomarkerkb.org/static/faq
        - REACT_APP_BASENAME=/
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=8080
    ports:
      - '8080:80'
networks:
  default:
    name: glygen-network-biom-dev
    external: true