version: '3.4'
services:
  frontend:
    container_name: glygen-biomarker-prod
    image: glygen-biomarker-prod:latest
    build:
      args:
        - REACT_APP_ENV=biom_prod
        - REACT_APP_BUILD=biomarker
        - REACT_APP_API=https://api.biomarkerkb.org
        - REACT_APP_DOMAIN=https://www.biomarkerkb.org
        # - REACT_APP_DOMAIN=http://localhost:6060
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.glygen.org
        - REACT_APP_SPARQL=https://sparql.glygen.org
        - REACT_APP_GITHUB=https://github.com/clinical-biomarkers/biomarker-partnership
        - REACT_BIOMARKER_DATA=https://data.biomarkerkb.org
        - REACT_APP_BASENAME=/
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=7070
    ports:
      - '7070:80'
networks:
  default:
    external:
      name: glygen-network-biom-prod